org: zmrfzn
app: otel-sam
service: otel-sam
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  tracing:
    lambda: true
    apiGateway: true

functions:
  api:
    handler: index.handler
    environment:
        AWS_LAMBDA_EXEC_WRAPPER: /opt/otel-handler
        OTEL_EXPORTER_OTLP_ENDPOINT: https://otlp.nr-data.net:4317
        OTEL_EXPORTER_OTLP_HEADERS: 'api-key=${ssm:/nr_experiments_ingest_key}'
        OTEL_SERVICE_NAME: otel-lambda-sls-otel-example
        # https://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/plugins/node/opentelemetry-instrumentation-aws-lambda#aws-lambda-instrumentation-options
        OTEL_LAMBDA_DISABLE_AWS_CONTEXT_PROPAGATION: true 
    events:
      - httpApi: '*'
    layers:
      - arn:aws:lambda:us-east-1:901920570463:layer:aws-otel-nodejs-amd64-ver-1-13-0:2

plugins:
  - serverless-offline
